// This will execute code in order to create validators
import './confirm/agree'
import './confirm/check'
import './confirm/confirm'
import './existence/ensureNew'
import './existence/exist'
import './existence/unique'
import './existence/required'
import './filter/trim'
import './filter/capitalize'
import './filter/lowercase'
import './filter/uppercase'
import './lifecycle/lifecycle'
import './size/eq'
import './size/max'
import './size/min'
